apiVersion: apps/v1
kind: Deployment

metadata:
  name: flask-devops-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: flask-devops-app

  template:
    metadata:
      labels:
        app: flask-devops-app

    spec:
      containers:
        - name: flask-devops-app

          image: flask-devops-app:latest

          ports:
            - containerPort: 5000

          env:
            - name: PORT
              value: "5000"

          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 20